# Vapor app compose
version: "2"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    #command: vapor run serve
    ports:
      - 8080:8080
    depends_on:
      - "db"
  db:
    image: mysql
    restart: always
    environment:
      #MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: friends
